name: Build Documentation

on:
  push:
    branches:
      - issue-83
  pull_request:
    branches:
      - issue-83

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: List files
        run: ls -l